// <auto-generated />
using System;
using AuthJwtbearer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthJwtbearer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthJwtbearer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7976f00c-5f2b-450c-a8df-e7af08426d72"),
                            Email = "abdumurodovnodirxon@gmail.com",
                            FirstName = "Nodir",
                            LastName = "Abdumurotov",
                            Password = "12345",
                            Role = 0,
                            UserName = "Nodirkhan"
                        },
                        new
                        {
                            Id = new Guid("e110a021-8fc4-4647-9002-e3abc56283be"),
                            Email = "doston@gmail.com",
                            FirstName = "Doston",
                            LastName = "Yoqubjonov",
                            Password = "54321",
                            Role = 1,
                            UserName = "Doston"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
